services:
  api-python:
    build:
      context: .
      dockerfile: apps/api-python/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}

  api-ruby:
    build:
      context: .
      dockerfile: apps/api-ruby/Dockerfile
    ports:
      - "3000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_LOG_TO_STDOUT=true

  web-react:
    build:
      context: .
      dockerfile: apps/web-react/Dockerfile
      args:
        VITE_API_BASE: http://localhost:8000
    ports:
      - "4200:80"
    depends_on:
      - api-python
      - api-ruby